### ISSUE TITLE
deep update on one to many composition

### ISSUE THREAD

**Issue by lellavasundhara** [sapmentors/cds-pg#116]
Hello Team,

I have an entity like below

```
entity Students {

key id: string(10);

name: string(30);

title: localized string(40);

}
```

I want to do deep update on Students entity.

I do put request.

My URL is 'http://localhost:4004/v2/StudentService/Students(1)'

and Payload is :

```
{ id : '1',

name: 'test',

texts:[{locale: 'en',title: 'Guntur'}]

}
```

It shows error like below

![deep update issue](https://user-images.githubusercontent.com/44637053/116879999-0f078400-ac3f-11eb-84da-9e9756c7a5ec.PNG)

I am using Node js with PostgreSQL Database. It's working SQLite Database.
 Please help me

**Comment by gregorwolf** [comment]
Hi @lellavasundhara ,

right now we've not used localized in our datamodel. It would be great if you can enhance the cds-pg project and add an Entity Styles to [__tests__/__assets__/cap-proj/db/schema.cds](https://github.com/sapmentors/cds-pg/blob/main/__tests__/__assets__/cap-proj/db/schema.cds). That would make a good example for a localized entity. Then also add a test that replicates the issue.

Best regards
Gregor

**Comment by tiger0328** [comment]
Hello @gregorwolf 
I ran into similar issue when try to update one to many composition.
Here is the model with one to many composition:

entity Req {
    key Id        : UUID;
        title     : String(100);
        amount    : Amount;
        status    : Status;
        comments  : String(1000);
        reqLines  : Composition of many ReqLines
                        on reqLines.req = $self 
}

entity ReqLines {
    key Id        : UUID;
        req       : Association to Req;
        item      : String(100);
        quantity  : Integer;
        price     : Price;
}

when I try to send the payload using PUT method  in postman like this:
![image](https://user-images.githubusercontent.com/86993032/125169700-f8048580-e1dd-11eb-9a1a-25f148a51e41.png)
Error messages:
![image](https://user-images.githubusercontent.com/86993032/125169742-1f5b5280-e1de-11eb-929e-bb101bb78aac.png)

The same use case works fine for sqlite. 

Best Regards and Thanks.

**Comment by vobu** [comment]
hi @tiger0328 - the same thing indeed applies to your example: you're using a pseudo-localized version of currency; that -as @gregorwolf pointed out- we do not yet have available in `cds-pg`.
And, as also @gregorwolf has pointed out above, "it would be great if you can enhance the cds-pg project and add an Entity Styles to tests/assets/cap-proj/db/schema.cds. That would make a good example for a localized entity. Then also add a test that replicates the issue."

**Comment by isreven** [comment]
Hello Team,

I have entities like below (with many to many relations) 

entity **WorkSpace** : managed {
      key ID               : String;
      Editable         : Boolean;
      WorkPages        : Composition of many { // many-to-many relationship
                                   key Instance : Association to WorkPage;
                             }
          Sites            : Association to many Site.WorkSpaces
                                   on Sites.Instance = $self; // many-to-many backlink
          Roles            : Association to many Role.WorkSpaces
                                   on Roles.Instance = $self; // many-to-many backlink
}

entity **Role** {
      key ID           : String;
      WorkSpaces   : Composition of many { // many-to-many relationship
                               key Instance : Association to WorkSpace;
                         }
}

When I tried to patch Specific Role with WorkSpaces
_PATCH {{path}}/Roles('R_1')_

We get the same error @lellavasundhara got.

version of cds-pg - 0.1.14
version of cds - 5.1.5
version of cds-dbm - 0.0.27
