### ISSUE TITLE
Evaluate if the NPM module knex might help to get multi DB Support

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#13]
According to the readme [knex](https://www.npmjs.com/package/knex) is a:

> multi-dialect (MSSQL, MySQL, PostgreSQL, SQLite3, Oracle (including Oracle Wallet Authentication)) query builder for Node.js

So we might be better off to translate cqn to knex instead of SQL. That way we would directly get support for other databases as well.

**Comment by mikezaschka** [comment]
While I kind of like the idea, I think the introduction of another layer in between the cds core and and an external database adapter would be too much overhead. The @sap/cds-runtime includes an SQL builder component, that is capable of translating CQN to SQL for all features CAP consists of and probably will be maintained by SAP in the future. While there is still a lack in the official documentation on this topic, I think extending the core builder with specific requirements will be the _official_ way to add support for other databases.  
We actually did this within the project (UPDATE and DELETE still need to be migrated to the builder though) and the code footprint of changes has been really small. 
With the experiences from within this project, I think the adoption of other databases might be relatively easy and the effort to write a full fledged CQN to knex compiler would require a lot more work.

**Comment by vobu** [comment]
i'm with @mikezaschka here - @gregorwolf: let's close this :)
