### ISSUE TITLE
CDS-PG deployment not working

### ISSUE THREAD

**Issue by mrkarthi** [sapmentors/cds-pg#130]
Hello,

I am using the latest cds-pg version (0.0.48) after the issue #121 is fixed (Thanks to @gregorwolf and the team).

I am not able to deploy the model to the database. I am not getting the below message when I deploy with 0.0.48 version. The deployment works with 0.0.41 version.
```
npx cds-pg deploy srv --to db

 > filling db.data from db\data\db-data.csv
/> successfully deployed to ./postgres
```

https://github.com/mrkarthi/pg-app

Thank you.

Regards,
Karthi M R.

**Comment by vobu** [comment]
please
- put in some debugging effort and find the source of the error
- use https://github.com/mikezaschka/cds-dbm for (delta-capable) deployment just as mentioned in https://github.com/sapmentors/cds-pg#cds-deployment
