### ISSUE TITLE
Support @sap/cds 5

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#139]
Due to changes on the structure cds-pg currently doesn't work with @sap/cds 5. Maybe @sjvans can guide us.

**Comment by sjvans** [comment]
@gregorwolf https://github.com/sapmentors/cds-pg/pull/140 should help a bit. i don't have the setup running locally to verify, though.

**Comment by gregorwolf** [comment]
All automated tests run fine for #140. Will merge as soon as the issue with GitHub Actions is resolved and the tests in GitHub also work.

**Comment by gregorwolf** [comment]
Fixed with #140

**Comment by vobu** [comment]
> i don't have the setup running locally to verify, though.

time to do that :) and it's easypeasy: https://github.com/sapmentors/cds-pg/blob/main/docs/CONTRIBUTING.md#setting-up-the-development-environment
thanks for your support on `cds 5`!
