### ISSUE TITLE
Association doesn't work as expected

### ISSUE THREAD

**Issue by octavonu** [sapmentors/cds-pg#143]
Hello,

Am I doing something wrong? 
Given the files bellow I am able to post an entry to the service Stores despite the fact that the Owner_ID doesn't exist.

The same example used with sqlite would return an error code: 'ASSERT_REFERENCE_INTEGRITY'

Thank you in advance,

../db/customers.cds

namespace customers;

type CountryCode : String(3); 

entity Owners {
    key ID   : String(3);
        Name : String(50);
}

entity Stores {
    key Owner   : Association to Owners;
    key Country : CountryCode;
    key Number  : Integer;
}

../srv/customers.cds

using {customers} from '../db/customers';

service ows {
    entity Stores as projection on customers.Stores;
    entity Owners as projection on customers.Owners;
}

# POST to Stores entity
POST http://localhost:4004/ows/Stores
Content-Type: application/json

{
    "Owner_ID": "TRO",
    "Country": "FR",
    "Number": 1
}

**Comment by vobu** [comment]
try replacing the association with a `composition of` for deep inserts
