### ISSUE TITLE
Not able to use External service using cds import "metadata.xml"

### ISSUE THREAD

**Issue by ibibhu** [sapmentors/cds-pg#167]
Dear Team,

Issue: Not able to use cds import in the cds-pg based CAP project

Steps I followed:- 

cds import "ZPDCDS_SRV.edmx"
 
Repository: https://github.com/ibibhu/cap-devtoberfest.git
Refer the below change set :- 
Change Set : https://github.com/ibibhu/cap-devtoberfest/commit/2216154910cbe329eaeb4b7a40266bf822ff0858

For running the project I used  : -

cds serve:

I cannot see the external service

![image](https://user-images.githubusercontent.com/5914863/123960349-d2e96900-d9cc-11eb-855e-bbaf832c0165.png)

cds watch

external service is running in mock mode

![image](https://user-images.githubusercontent.com/5914863/123960385-dc72d100-d9cc-11eb-95f2-a430d29d18b2.png)

but while accessing the oData it's giving the below message
 
![image](https://user-images.githubusercontent.com/5914863/123960827-63c04480-d9cd-11eb-99a9-555c4c240984.png)

I tried the same steps with a simple cap project

cds init 
cds import "ZPDCDS_SRV.edmx"

cds watch or cds serve, I can get empty results and service is also exposed

![image](https://user-images.githubusercontent.com/5914863/123960665-307db580-d9cd-11eb-91c3-c17feca1e2d4.png)

Can someone please help me , is this a bug or am doing something wrong.

Goal was to consumer external api/odata in this project using "cds import"

Thanks and Regards,
Bibhu

**Comment by vobu** [comment]
`cds serve all --with-mocks` should work for you

**Comment by ibibhu** [comment]
Tried the same but getting the same result:

cds serve all --with-mocks
![image](https://user-images.githubusercontent.com/5914863/124002225-1b1b8200-d9f3-11eb-957b-c3b4751fe759.png)

oData Request
![image](https://user-images.githubusercontent.com/5914863/124002149-03dc9480-d9f3-11eb-800d-a29ccfea9d64.png)

Error Log
![image](https://user-images.githubusercontent.com/5914863/124002376-47cf9980-d9f3-11eb-8f3f-905f3ddb0df5.png)

**Comment by vobu** [comment]
sorry, out of my wits here - have you tried with `sqlite` as db?

**Comment by ibibhu** [comment]
Yes, same thing works with sqlite db

**Comment by vobu** [comment]
so would you be able to debug/break into both `cds-pg` and `sqlite` at `cds import`-time and/or runtime and find out what's different?
