### ISSUE TITLE
Localized Language is not working

### ISSUE THREAD

**Issue by parthjhalani** [sapmentors/cds-pg#196]
Hi Mentors,

For my project, I wanted to use Localized languages. 
I created my data model like this
`entity ProductCategory {
    key categoryid : Integer;
        name        : localized String;        
}`

And than exposed it like below
`@readonly entity ProductsCategory as projection on ProductCategory;`

I also created some CSV to upload the sample data with file names _ProductCategory.csv_ and _ProductCategory_texts.csv_

When i use it on sqlite.. I can access the localized data by passing the url parameter sap-language=DE. However the same doesn't work when i use postgresql as db. The metadata for postgresql does show the generated text table so that means the data tables are all generated fine.
![image](https://user-images.githubusercontent.com/6260514/130135715-08a6a217-c1a5-40d6-8ac8-0b985c6716f9.png)

Url called to get localized data
_**/ProductsCategory?sap-language=DE**_

Please note that same works fine for sqlite DB.

Thanks,
Parth

**Comment by vobu** [comment]
yep, no support of localized entities yet in cds-pg. 
also see #116 and #104. 
any help appreciated, PRs welcome!
