### ISSUE TITLE
Issue on "any" function of OData protocol

### ISSUE THREAD

**Issue by tiger0328** [sapmentors/cds-pg#199]
Hi Team

I came across an issue when try to use GET method to retrieve the data via OData protocol.
There are two key entities in my application, one is PurchaseOrder, the other is POLineItem, also there is a composition navigation attribute in PurchaseOrder called poLines, which is point to POLineItem.
I try to filter the PurchaseOrder data by constraining an field in POLineItem us the bellow query:
http://XXXXXXXX:XXXX/polling/PurchaseOrder?$filter=poLines/any(pl:pl/id eq afc315a6-5db5-49bb-bbb3-32d74daceda0)
![image](https://user-images.githubusercontent.com/86993032/132088102-2584c904-6f63-4db4-a38b-d946a598f5ee.png)

but errors pops up like:

{
    "error": {
        "code": "42601",
        "message": "syntax error at or near \"foreign\""
    }
}
I checked the call stack and found the errors in there 
/node_modules/pg-protocol/dist/parser.js:287:98
![image](https://user-images.githubusercontent.com/86993032/132088112-ef586df0-77d4-4658-a342-cbdd1a5fe1de.png)

is there any other ways to filter the PurchaseOrder by filtering the filed in POLineItem? thanks.

**Comment by vobu** [comment]
this sounds to me as if it might be an issue with supporting the OData v4 `$filter` `any` in general within CAP, and nothing `cds-pg`-specific.
i had a quick glance through the core OData modules/runtimes, but couldn't find anything related to supporting the `any` lambda operator.
please try:
- updating `@sap/cds` to the latest version, then re-run your example query
- switching the persistence to sqlite and see if the lambda `any` works in there

**Comment by gregorwolf** [comment]
Hi @tiger0328,

I've created a test in the PR #253. I can't replicate your issue.

Best Regards
Gregor
