### ISSUE TITLE
Error: No service definition found for 'postgres'

### ISSUE THREAD

**Issue by pwasem** [sapmentors/cds-pg#225]
Hi,

recently I am getting below error when running `npx cds-pg deploy app --to postgres`:

```shell
node ➜ /workspaces/cap-ratings $ npm run deploy       

> cap-ratings@0.1.0 deploy
> npx cds-pg deploy app --to postgres

[cds.connect] - No service definition found for 'postgres', as required by 'cds.requires.postgres': {
  impl: 'cds-pg',
  model: [ 'app' ],
  credentials: {
    host: 'postgres-svc',
    port: '5432',
    user: 'slonik',
    password: 'topsekret',
    database: 'cap-ratings',
    schema: 'public'
  }
}
(node:19603) UnhandledPromiseRejectionWarning: Error: No service definition found for 'postgres'
    at AsyncFunction.connect.to (/workspaces/cap-ratings/node_modules/@sap/cds/lib/connect/index.js:42:11)
    at async Object.to (/workspaces/cap-ratings/node_modules/@sap/cds/lib/deploy.js:21:23)
    at async deploy (/workspaces/cap-ratings/node_modules/cds-pg/bin/cds-pg.js:11:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19603) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19603) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
node ➜ /workspaces/cap-ratings $ 
```

Project setup look as follows:

**cds**

```shell
node ➜ /workspaces/cap-ratings $ cds -v
@sap/cds: 5.5.4
@sap/cds-compiler: 2.7.0
@sap/cds-dk: 4.5.3
@sap/cds-foss: 3.0.0
@sap/cds-odata-v2-adapter-proxy: 1.7.12
@sap/eslint-plugin-cds: 2.1.1
Node.js: v14.17.6
cap-ratings: 0.1.0
home: /workspaces/cap-ratings/node_modules/@sap/cds
```

**.cdsrc.json**

```json
{
  "features": {
    "fiori_preview": true
  },
  "requires": {
    "db": {
      "kind": "postgres"
    },
    "postgres": {
      "impl": "cds-pg",
      "model": [
        "app"
      ]
    }
  }
}
```

**default-env.json**

```json
{
  "PORT": 5005,
  "VCAP_SERVICES": {
    "postgres": [
      {
        "name": "postgres",
        "label": "postgres",
        "tags": [
          "postgres"
        ],
        "credentials": {
          "host": "postgres-svc",
          "port": "5432",
          "user": "slonik",
          "password": "topsekret",
          "database": "cap-ratings",
          "schema": "public"
        }
      }
    ]
  },
  "DEBUG": "ratings-service"
}
```

**package.json**

```json
{
  "name": "cap-ratings",
  "version": "0.1.0",
  "description": "A simple CAP project.",
  "private": true,
  "dependencies": {
    "@sap/cds": "^5.5.4",
    "@sap/cds-odata-v2-adapter-proxy": "^1.7.12",
    "cds-pg": "^0.1.13",
    "express": "^4.17.1",
    "helmet": "^4.6.0",
    "passport": "^0.5.0"
  },
  "devDependencies": {
    "@sap/eslint-plugin-cds": "^2.1.1",
    "eslint": "^7.32.0",
    "eslint-config-standard": "^16.0.3",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^5.1.0",
    "sqlite3": "^5.0.2"
  },
  "scripts": {
    "deploy": "npx cds-pg deploy app --to postgres",
    "watch": "cds watch",
    "mock": "cds run --with-mocks --in-memory",
    "prestart": "npm run deploy",
    "start": "npx cds run",
    "build": "cds build",
    "predocker": "npm run build",
    "docker": "docker build -t pwasem/cap-ratings:latest ."
  }
}
```

Maybe an issue with recent `@sap/cds-dk` or `sap/cds` versions?

Thank you in advance for having a look!

Best regards,

Pascal

**Comment by sebastianesch** [comment]
Hi @pwasem,

The problem is in your default-env.json and in your deployment command.

In your default-env.json make sure to have the tags `plain` and/or `db` and in your deploy command you need to follow the example in the [cds-pg README](https://github.com/sapmentors/cds-pg/blob/main/README.md#cds-deployment): `npx cds-pg deploy srv --to db`.

CAP merges the requires sections "db" and "postgres" in your `package.json` and actually forgets the "postgres" service and looks for the "db" service. That's why the deploy command has `--to db` as a parameter. The "kind" information is also stripped during merging of the configuration values and only the "dialect" is left.

CAP then checks if there is a VCAP service whose name matches the service name (`db`), whose tag matches the `context + ':' +  service name` (`cds:db`), whose tag match the dialect or kind (`plain` and `undefined`) or whose label matches the dialect or kind. See @sap/cds/lib/env/index.js - function `_add_vcap_services_to`.

Kind regards,
Sebastian

**Comment by sjvans** [comment]
hi @pwasem @gregorwolf @sebastianesch 

regarding the original error, please see https://cap.cloud.sap/docs/advanced/troubleshooting#why-does-the-server-crash-with-no-service-definition-found-for-srv-name

deploy to db bypasses this, because the service name lookup isn’t done for the well-known requires property „db“.

best,
sebastian

**Comment by pwasem** [comment]
> Hi @pwasem,
> 
> The problem is in your default-env.json and in your deployment command.
> 
> In your default-env.json make sure to have the tags `plain` and/or `db` and in your deploy command you need to follow the example in the [cds-pg README](https://github.com/sapmentors/cds-pg/blob/main/README.md#cds-deployment): `npx cds-pg deploy srv --to db`.
> 
> CAP merges the requires sections "db" and "postgres" in your `package.json` and actually forgets the "postgres" service and looks for the "db" service. That's why the deploy command has `--to db` as a parameter. The "kind" information is also stripped during merging of the configuration values and only the "dialect" is left.
> 
> CAP then checks if there is a VCAP service whose name matches the service name (`db`), whose tag matches the `context + ':' + service name` (`cds:db`), whose tag match the dialect or kind (`plain` and `undefined`) or whose label matches the dialect or kind. See @sap/cds/lib/env/index.js - function `_add_vcap_services_to`.
> 
> Kind regards, Sebastian

@sebastianesch 


How should the actual `default-env.json` look in this case?

Thx!

**Comment by sebastianesch** [comment]
Hi @pwasem,

change your .cdsrc.json to add the dialect to the postgres section:

```
{
  "features": {
    "fiori_preview": true
  },
  "requires": {
    "db": {
      "kind": "postgres"
    },
    "postgres": {
      "dialect": "plain", // << Add the dialect
      "impl": "cds-pg",
      "model": [
        "app"
      ]
    }
  }
}
```
And change your default-env.json to the tags "plain" and "db":

```
{
  "PORT": 5005,
  "VCAP_SERVICES": {
    "postgres": [
      {
        "name": "postgres",
        "label": "postgres",
        "tags": ["plain", "db"], // << Change the tags here
        "credentials": {
          "host": "postgres-svc",
          "port": "5432",
          "user": "slonik",
          "password": "topsekret",
          "database": "cap-ratings",
          "schema": "public"
        }
      }
    ]
  },
  "DEBUG": "ratings-service"
}
```

That should do the trick.

Cheers,
Sebastian
