### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by T1mey** [sapmentors/cds-pg#232]
Hi,

I'm working on an app which should use a pg db. I'm follwing the tutorials but have some questions:

How does cds-pg is looking up the credentials on BTP? I have boud my database to the application. So I can see the credentials.
I do not want to put them in package.json ... but without that I get an error

error: no pg_hba.conf entry for host "x.x.x.x", user "XXX", database "XXX", SSL off

Any idea how to force looking them up ?

**Comment by gregorwolf** [comment]
Please try the latest updates of [pg-beershop](https://github.com/gregorwolf/pg-beershop). Build and deploy the project. It uses the credentials that are provided via the VCAP_SERVICES environment variable.

**Comment by T1mey** [comment]
Thanks... Will try asap...

**Comment by T1mey** [comment]
Hi @gregorwolf ,

this solved the problem. Thanks a lot for your support. 
Is the change of the user and password after each deployment a wanted behaviour ?

Maybe this can be documented on cds-pg pages ?

**Comment by gregorwolf** [comment]
The credential change is a default behaviour of the Cloud Foundry environment. If you need a permanent key i.e. to access the DB as a developer you have to create a service key.
