### ISSUE TITLE
timestamp conversion issue

### ISSUE THREAD

**Issue by rbhuva** [sapmentors/cds-pg#241]
Hi,

When we define a field with type = timestamp, it is created into DB as "timestamp without time zone".

While creating a new entry from the UI side using the OData model, it passes value in TZ format in the batch request which is saved in DB without a time zone.

In a case where there is a timezone different then UTC, it is saving wrong values.

createdat and modifiedat are just showing wrong values when Application is running on other than UTC time zone.

Thanks,
Rajdeep Bhuva

**Comment by gregorwolf** [comment]
Hi @rbhuva,

it would help if you could provide the sample OData request or maybe directly send a pull request enhancing the unit tests.

Best Regards
Gregor

**Comment by rbhuva** [comment]
Hi @gregorwolf,

I have added the fix with the test cases on the pull request: https://github.com/sapmentors/cds-pg/pull/243
Kindly review the pull request.

Thanks,
Rajdeep Bhuva

**Comment by narmbruster** [comment]
Hi @rbhuva,

thanks for working on this topic. During our tests we also found that the "milli-seconds" were swallowed up by 
const convertToISO = (element) => {
return new Date(element + 'Z').toISOString()
}
Example:
data written: 2012-12-03T07:16:23.574Z
date read:  2012-12-03T07:16:23.000Z   (output of convertToISO)

Kindly check if a "loopback" test might be added to the test implementation (just to ensure that both values match). Something like:

      test(' -> Timestamp', async () => {
        const value = '2012-12-03T07:16:23.574Z';
        const response = await request.post('/beershop/TypeChecks').send({
          type_Timestamp: value,
        })
        expect(response.status).toStrictEqual(201)

        const verify = await request.get(`/beershop/TypeChecks(${response.body.ID})`).send()
        expect(verify.body.type_Timestamp).toStrictEqual(value);
      })

**Comment by rbhuva** [comment]
Hi @narmbruster,

As per your suggestion, I have added the loopback test. Both values are matching along with milliseconds.

Regards,
Rajdeep Bhuva

**Comment by gregorwolf** [comment]
Thank you @narmbruster for the improvement of the PR from @rbhuva. I've created a new version and will close this issue.
