### ISSUE TITLE
error: column reference "id" is ambiguous

### ISSUE THREAD

**Issue by austinkloske22** [sapmentors/cds-pg#246]
When simultaneously expanding and filtering, I ran into the error:  "column reference "id" is ambiguous". This error seems to only impact when attempting to filter on an expanded CDS key field.

url: http://localhost:5001/Tenant/Shipping/Shipments(74664430-0bd0-11ec-9a03-0242ac130003)?$expand=toShipUnits($filter=ID%20eq%2007182320-0bf4-11ec-9a03-0242ac130003)

![image](https://user-images.githubusercontent.com/45456027/145035963-27f4f4da-01d2-4bcc-b456-885be4da50a2.png)

for example, swapping "ID" to "Shipment_ID" results in a successful query: http://localhost:5001/Tenant/Shipping/Shipments(74664430-0bd0-11ec-9a03-0242ac130003)?$expand=toShipUnits($filter=Shipment_ID%20eq%2007182320-0bf4-11ec-9a03-0242ac130003)

![image](https://user-images.githubusercontent.com/45456027/145036272-b8f33720-0fca-4177-bb4b-da4231de7666.png)

**Comment by gregorwolf** [comment]
Hi @austinkloske22,
would be great if you can create a test case that can be replicated with our beer shop example data. For a quick start you could create a pull request with a sample REST client request added to the folder:

__tests__/__assets__/cap-proj/rest-client-test

Thanks
Gregor

**Comment by gregorwolf** [comment]
Hi @austinkloske22,
please check my branch https://github.com/gregorwolf/cds-pg/tree/column-reference-ambiguous-246. I'm not able to replicate your issue. Please add your sample request that does show your issue in our data model.

**Comment by austinkloske22** [comment]
@gregorwolf I apologize I've not been active on git and missed that you followed up on my issue. I will attempt to replicate the issue this week. 

One challenge for me is that I froze my project(s) on older npm release because of the trouble I had building & deploying with newer cds-dbm releases. My project w/ column reference "id" is ambiguous issue is on releases:
 
`"@sap/cds": "5.3.2"`,
`"cds-dbm": "0.0.24"`,
`"cds-pg": "0.0.41"`

What releases should I be using and as a cds-pg community how do we know what versions match @sap/cds releases? Perhaps my issue doesn't even exists when using the latest sap/cds release.

What release levels do you want me to replicate on? pg-beershop does not deploy to docker on the current repos version levels. I see there haven't been a new cds-dbm release on npm for 6 months.

![image](https://user-images.githubusercontent.com/45456027/147654910-fea0cff2-ca04-4150-94da-5d41ef997fe3.png)

**Comment by austinkloske22** [comment]
@gregorwolf - this issue has been resolved in one of the newer releases. In order to deploy pg-beershop and create the DB, I needed to lower the npm releases to:

```
"@sap/cds": "5.3.2",
"cds-dbm": "0.0.24",
"cds-pg": "0.0.41"
```
able to replicate:
http://localhost:4004/beershop/Breweries(0465e9ca-6255-4f5c-b8ba-7439531f8d28)?$expand=beers($filter=ID%20eq%2008d5b3fb-549c-4be7-9ac8-e039d75823e7)

![image](https://user-images.githubusercontent.com/45456027/147665119-a121fd1c-ac6e-4803-94ff-a17b56821da5.png)


http://localhost:4004/beershop/Breweries(0465e9ca-6255-4f5c-b8ba-7439531f8d28)?$expand=beers($filter=abv%20eq%200)

![image](https://user-images.githubusercontent.com/45456027/147665670-645c3eb4-603a-408d-9afb-0ed723172cd4.png)


After created / deploying, I'm able to update the cds / dbm, pg releases to newer releases the error does not occur. I need to get my cds, dbm, cds-pg versions updated. I'll close this issue.

"@sap/cds": "5.7.3",
"cds-dbm": "0.0.27",
"cds-pg": "0.1.16"
 
http://localhost:4004/beershop/Breweries(0465e9ca-6255-4f5c-b8ba-7439531f8d28)?$expand=beers($filter=ID%20eq%2008d5b3fb-549c-4be7-9ac8-e039d75823e7)

![image](https://user-images.githubusercontent.com/45456027/147665841-d6c10962-208b-4f40-a925-582b4ea3698f.png)
