### ISSUE TITLE
Tags in VACP Service Definition for PostgreSQL Credentials 

### ISSUE THREAD

**Issue by sebastianesch** [sapmentors/cds-pg#263]
I faced the problem that my connection information from default-env.json was not picked up when I followed the example in the README.md:

```
{
  "VCAP_SERVICES": {
    "postgres": [
      {
        "name": "postgres",
        "label": "postgres",
        "tags": ["postgres"],
        "credentials": {
          "host": "localhost",
          "port": "5432",
          "database": "dbname",
          "user": "postgres",
          "password": "postgres",
          "schema":"public"
        }
      }
    ]
  }
}
```

I figured out, when I follow the example from Gregors https://github.com/gregorwolf/pg-beershop the default-env.json is slightly different:

```
{
  "VCAP_SERVICES": {
    "postgres": [
      {
        "name": "postgres",
        "label": "postgres",
        "tags": ["plain", "database"],
        "credentials": {
          "host": "localhost",
          "port": "5432",
          "database": "beershop",
          "user": "postgres",
          "password": "postgres"
        }
      }
    ]
  }
}
```

Switching the tags from "postgres" to "plain" and "database" makes the difference. I don't know if this is an issue how cds-pg identifies the service definition or if it works as intended and the README.md needs to be adjusted.

Kind regards,
Sebastian

**Comment by vobu** [comment]
ah, good catch - we had the `dialect` resp `tags` thingie documented for `package.json` (see README.md), but were obviously missing the corresponding entry for the `default-env.json` example - mind submitting a PR for this? would be rad 🚀

**Comment by sebastianesch** [comment]
Hi Volker, 

I'm happy to contribute a pull request. But I would like to understand how exactly the credentials are read from the environment. 

I'm not sure if this part of cds-pg or cds itself. Looking at https://github.com/sapmentors/cds-pg/blob/main/lib/pg/Service.js I would think that cds provides the options and credentials to the constructor, but the description in CAP how services are located (https://cap.cloud.sap/docs/node.js/cds-connect#vcap_services) and the fact that apparently the dialect in the cds-pg config is important makes no sense to me.

Kind regards,
Sebastian

**Comment by sebastianesch** [comment]
I have submitted PR #264.

**Comment by gregorwolf** [comment]
Thank you.
