### ISSUE TITLE
cds terminates unexpectly

### ISSUE THREAD

**Issue by sedacrivity** [sapmentors/cds-pg#297]
Hi,

We had a weird issue where cds would spawn ( normal cds run, watch, .. ) and it would successfully launch showing all standard log messages and then the process would terminate immediately ...

This was happening with a new onboarded dev so we initially assumed a node or cds installation issue. We spend many hours trying to pin point the issue but could not find a resolution.

Then later on it happened to me as well ...

And then I realized the issue ....

The local docker postgresql instance was running fine but it had not yet a created DB.  Then the CDS process just terminates without giving any kind of (error) message.

I am not sure this is controlled by cds-pg but it would be nice to show some kind of message stating that 'Connection successful but no db 'x' was found ...'.  

That would have saved us many hours and a headache ...

Thanks,

Steven

**Comment by gregorwolf** [comment]
Would be great if you can create a PR with a test that shows this issue.

**Comment by sedacrivity** [comment]
> Would be great if you can create a PR with a test that shows this issue.

Can you elaborate a bit on what you would expect as 'test' ?  

The test is quite simple :

- just start your local docker instance
- remove the existing DB that is configured for the project
- execute `cds run`

Now interesting enough I just tried this on your beershop example and there the cds does not quit.  And it simply serves the api and then gives a return error within the api 

`<error xmlns="http://docs.oasis-open.org/odata/ns/metadata">
<code>3D000</code>
<message>database "beershop" does not exist</message>
</error>`

So not sure why it is behaving differently on mine .. hmmmm.
