### ISSUE TITLE
$filter in an expand doesn't work

### ISSUE THREAD

**Issue by AlexandreCordaJunior** [sapmentors/cds-pg#305]
Hi.

I downloaded the pg-beershop project and I started to test some APIs, but then I could not filter an expanded entity.
I tried doing the following query and it throw this error:

http://localhost:4004/beershop/Beers?$count=true&$select=ID,abv,ibu,name&$expand=brewery($select=ID,name)&$filter=brewery/name eq 'asd'&$skip=0&$top=30

https://ibb.co/MBy9Kcd

And it throws this error in the console:

[cds] - error: missing FROM-clause entry for table "brewery"
    at Parser.parseErrorMessage (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/alexandre/pg-beershop/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:126:14) {
  length: 118,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '73',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3541',
  routine: 'errorMissingRTE',
  id: '1541585',
  level: 'ERROR',
  timestamp: 1652712172856
}

Is this filter available right now or will it be implemented in the future?

Thanks

**Comment by gregorwolf** [comment]
For better analysis of the issue please run your project with the environment variable:

DEBUG=cds-pg

set to get the generated SQL shown.

**Comment by AlexandreCordaJunior** [comment]
Sorry for the delay.
This are the logs shown in the console:

[cds] - GET /beershop-admin/Beers?$filter=brewery/name eq ''&$expand=brewery 
[cds-pg] - sql >  SELECT a.ID AS "a_ID", a.name AS "a_name", a.abv AS "a_abv", a.ibu AS "a_ibu", a.brewery_ID AS "a_brewery_ID", b.ID AS "b_ID", b.name AS "b_name", $1 AS "b_IsActiveEntity", $2 AS "b_HasActiveEntity", CASE WHEN B_DRAFTS.DRAFTADMINISTRATIVEDATA_DRAFTUUID IS NOT NULL THEN TRUE ELSE FALSE END AS "b_HasDraftEntity" FROM BeershopAdminService_Beers a LEFT JOIN BeershopAdminService_Breweries b ON ( b.ID = a.brewery_ID ) LEFT JOIN BeershopAdminService_Breweries_drafts b_drafts ON ( b_drafts.ID = b.ID ) WHERE a.brewery.name = $3 ORDER BY a.ID ASC LIMIT 1000 OFFSET 0
[cds-pg] - values >  [ true, false, '' ]

**Comment by negativename** [comment]
Hello. 
We have encountered the same error. We analyzed it and realized that it is related to the way SAP CDS handles references. For example in your SQL statement above you filter breweries by name using association:

> a.brewery.name

This SQL statement is not supported by PostgreSQL. It is suitable for SAP Hana, but for PostgreSQL we should process the association with INNER JOIN.

Please see below the code from CDS that is responsible for creation of this dot-association:
<img width="995" alt="Screenshot 2022-07-16 at 14 32 40" src="https://user-images.githubusercontent.com/42915533/179353147-59e4497c-f088-440d-979b-f50bb4541d44.png">

As CDS is closed source, I can't propose to change it to more widely supported INNER JOIN construction.

One of the ideas is to revise SQL queries within cds-pg by replacing dot-associations with inner joins. We are not sure this is the best solution.

What do you think? Do you have any other ideas?

**Comment by gregorwolf** [comment]
Hi @negativename,

when needed we need to adjust the SQL in cds-pg. So it would be great if you can contribute this.

**Comment by negativename** [comment]
Hello, 
I've created a pull request

**Comment by lirudayam** [comment]
Hello everyone
This looks like a great fix, is it possible to merge the PR asap? We have a project on CAP with PostgreSQL and this would be very helpful, if expanded $filters are possible, since we have many occurrences in our project which we tested locally on SQLite.

**Comment by vobu** [comment]
unfortunately the tests in #335 still fail - if you need this asap, would you mind taking a look at the failing tests and eventually contribute the fix onto the PR?
