### ISSUE TITLE
UPDATE Errors on CAP with PostgreSQL

### ISSUE THREAD

**Issue by sonjadeissenboeck** [sapmentors/cds-pg#349]
Upon updating one entity in our application, we receive the following error on the BTP: 
`[cds] - error: current transaction is aborted, commands ignored until end of transaction block`

and in the frontend:
`Request failed with status code 500 - Internal Server Error : MERGE Receiver(guid'XXX')`

Weirdly enough, this error is only occurring on this "Receiver"-entity. All other entities can be updated without any problems.

For the update, we are using generic CAP handlers, nothing customized.

We assume that this is a problem with the PostgreSQL drivers and would really appreciate any support or guidance on how to quickly fix this.

**Comment by vobu** [comment]
Unfortunately there's not enough context info here to provide any support.
Alas: please specify:
- what PostgreSQL version on what hyperscaler? 
- Node.js version
- `cds-pg` version
- sample code: e.g. `Receiver` entity

At best, we'd be really happy with a minimal working example so we can also check runtime behavior.

**Comment by sonjadeissenboeck** [comment]
Thank you for your answer. We eventually were able to solve our problem by replicating the environment locally and doing some intensive debugging where we found a GROUP BY error. 
Maybe the cds-pg drivers could be enhanced with some error handlings and meaningful logs? I think this would immensely increase the user-friendliness of using PostgreSQL! :)

**Comment by gregorwolf** [comment]
Dear @sonjadeissenboeck,

please don't hessitate to provide a pull request with improvements.
