### ISSUE TITLE
Run cds-pg with Azure Cosmos DB for PostgreSQL distributed SQL API

### ISSUE THREAD

**Issue by MartinPankraz** [sapmentors/cds-pg#355]
Dear sap mentors and contributors,

SAP added Private Link support to CosmosDB [recently](https://help.sap.com/docs/PRIVATE_LINK/42acd88cb4134ba2a7d3e0e62c9fe6cf/663ed5631cfd4ef0a4bd89ca00266943.html). Also there are ideas to design distributed CAP apps across multiple BTP regions. For a true setup a distributed database is required.

Any desire to collaborate on this and enable CAP to consume CosmosDB? [Soontao](https://github.com/Soontao) shared that the PostgreSQL API of Cosmos might be best fit given the nature of CAP. Appreciate your thoughts.

KR
Martin

**Comment by vobu** [comment]
totally up for it!
we'll need to wait until next week though as we're meeting with the CAP core team to align how to best (co-) maintain `cds-pg` going forward.
I'll check back in here.
