### ISSUE TITLE
Case-sensitive issue in filter operation

### ISSUE THREAD

**Issue by ajewelbd** [sapmentors/cds-pg#358]
Hi,
We are facing case-sensitive issue while filter from ui5.
Suppose, a column value is stored as 'Flush'. If we filter from ui5 'Fl', then we get the data.
But if we write 'fl', we get no data.

Best regards.
Md. Ashraful Alam

**Comment by gregorwolf** [comment]
Hi @ajewelbd,

to help finding a solution it would be great if you could create a pull request that shows your issue in a new test request that you add to:

__tests__/__assets__/cap-proj/rest-client-test/beers.http

To replicate the behaviour of your UI5 app it's the best to look at the Network tab in the developer tools.

Best Regards
Gregor

**Comment by ajewelbd** [comment]
Hi @gregorwolf,
Thanks a lot for reply.

URLs:
Working: http://localhost:40004/my-service/CustomersViewEN?$filter=contains(name,'Fl')

Nor working: http://localhost:40004/my-service/CustomersViewEN?$filter=contains(name,'fl')

Thanks.

**Comment by gregorwolf** [comment]
Have you tested if it works with sqlite?

**Comment by ajewelbd** [comment]
Yah, It is properly working in SQLite, But, not in postgre.

**Comment by ajewelbd** [comment]
Hi.

I think i found the issue. In postgre LIKE operator is case-sensitive.
But, if we use ILIKE then it is woks fine.

If I am not wrong, in cds-pg 'LIKE' operator is used.

Thanks.

**Comment by gregorwolf** [comment]
Would be great if you can contribute the improvement via a pull request.
