### ISSUE TITLE
Invalid SQL query when Draft Entity make reference to other Draft Entity in OData call.

### ISSUE THREAD

**Issue by ryegrosT8** [sapmentors/cds-pg#367]
Hi there,

First of all, thank very much guys for the cds-pg library initiative. It is really a very good alternative for those doing projects that doesn’t require all the power of the Hana Database and want to deliver to customer’s a less expensive options at SAP Cloud BTP. This is my case, by the way.

I’m new to CDS world, so I’m not sure if a found a bug or if I did something wrong. I’m using Fiori Elements to build CRUD’s on the entities exposed by cds/cds-pg, but when I expose two entities using “@odata.draft.enable” and try to make a “matchcode”/”combobox” on the first entity referencing the second entity in “CollectionPath” annotatons, I receive an “SQL FROM-clause error”.

To reproduce the issue at cds-pg test layer, I had created a new fork into the project https://github.com/ryegrosT8/cds-pg, the entities Supplier and Bottle was added at db/schema.cds and also published on srv/beershop-service.cds with the needed annotations at srv/ui-annotations.cds and db/schema.cds to show the “matchcode”/”combobox” on a possible Fiori Element’s screen.

The test case “Draft entity referencing another draft entity on matchcode call” have a reduced query made by a Fiori Elements screen that triggers the error:

OData Query:
/beershop/Suppliers?$filter=(IsActiveEntity eq false or SiblingEntity/IsActiveEntity eq null)&$expand=bottle

Response:
{"error":{"code":"42P01","message":"invalid reference to FROM-clause entry for table "beershopservice_bottles_drafts"}}

The query generated by the cds-pg parser:

```{sql, attr.source='.numberLines'}
SELECT a.ID AS "a_ID",
  a.name AS "a_name",
  a.country AS "a_country",
  a.bottle_ID AS "a_bottle_ID",
  b.ID AS "b_ID",
  b.name AS "b_name",
  b.size AS "b_size",
  b.color AS "b_color",
  $1 AS "b_IsActiveEntity",
  $2 AS "b_HasActiveEntity",
  CASE
    WHEN B_DRAFTS.DRAFTADMINISTRATIVEDATA_DRAFTUUID IS NOT NULL THEN TRUE
    ELSE FALSE
  END AS "b_HasDraftEntity",
  a.IsActiveEntity AS "a_IsActiveEntity",
  a.HasActiveEntity AS "a_HasActiveEntity",
  a.HasDraftEntity AS "a_HasDraftEntity"
FROM (
    SELECT ALIAS_1.ID AS ID,
      ALIAS_1.name AS name,
      ALIAS_1.country AS country,
      ALIAS_1.bottle_ID AS bottle_ID,
      IsActiveEntity AS IsActiveEntity,
      HasActiveEntity AS HasActiveEntity,
      HasDraftEntity AS HasDraftEntity,
      DraftAdministrativeData_DraftUUID AS DraftAdministrativeData_DraftUUID
    FROM BeershopService_Suppliers_drafts ALIAS_1
      INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON ALIAS_1.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID
    WHERE filterAdmin.InProcessByUser = $3
    UNION ALL
    SELECT ID AS ID,
      name AS name,
      country AS country,
      bottle_ID AS bottle_ID,
      $4 AS IsActiveEntity,
      $5 AS HasActiveEntity,
      CASE
        WHEN (
          SELECT 1
          FROM BeershopService_Suppliers_drafts ALIAS_2
          WHERE ALIAS_1.ID = ALIAS_2.ID
        ) IS NOT NULL THEN TRUE
        ELSE FALSE
      END AS HasDraftEntity,
      (
        SELECT DraftAdministrativeData_DraftUUID AS DraftAdministrativeData_DraftUUID
        FROM BeershopService_Suppliers_drafts ALIAS_2
        WHERE ALIAS_1.ID = ALIAS_2.ID
      )
    FROM BeershopService_Suppliers ALIAS_1
    WHERE NOT EXISTS (
        SELECT 1
        FROM BeershopService_Suppliers_drafts ALIAS_2
          INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON ALIAS_2.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID
        WHERE filterAdmin.InProcessByUser = $6
          AND ALIAS_1.ID = ALIAS_2.ID
      )
  ) AS a
  LEFT JOIN (
    SELECT BeershopService_Bottles_drafts.ID AS ID,
      BeershopService_Bottles_drafts.name AS name,
      BeershopService_Bottles_drafts.size AS size,
      BeershopService_Bottles_drafts.color AS color,
      IsActiveEntity AS IsActiveEntity,
      HasActiveEntity AS HasActiveEntity,
      HasDraftEntity AS HasDraftEntity,
      DraftAdministrativeData_DraftUUID AS DraftAdministrativeData_DraftUUID
    FROM BeershopService_Bottles_drafts
      INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON BeershopService_Bottles_drafts.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID
    WHERE filterAdmin.InProcessByUser = $7
    UNION ALL
    SELECT ID AS ID,
      name AS name,
      size AS size,
      color AS color,
      $8 AS IsActiveEntity,
      $9 AS HasActiveEntity,
      CASE
        WHEN (
          SELECT 1
          FROM BeershopService_Bottles_drafts HasDraftEntity    <-- == WEIRD ALIAS HERE ==
          WHERE (
              BeershopService_Bottles.ID = BeershopService_Bottles_drafts.ID
            )
        ) IS NOT NULL THEN TRUE
        ELSE FALSE
      END AS HasDraftEntity,
      (
        SELECT DraftAdministrativeData_DraftUUID AS DraftAdministrativeData_DraftUUID
        FROM BeershopService_Bottles_drafts
        WHERE (
            BeershopService_Bottles.ID = BeershopService_Bottles_drafts.ID
          )
      )
    FROM BeershopService_Bottles
    WHERE NOT EXISTS (
        SELECT 1
        FROM BeershopService_Bottles_drafts
          INNER JOIN DRAFT_DraftAdministrativeData filterAdmin ON BeershopService_Bottles_drafts.DraftAdministrativeData_DraftUUID = filterAdmin.DraftUUID
        WHERE (filterAdmin.InProcessByUser = $10)
          AND (
            BeershopService_Bottles.ID = BeershopService_Bottles_drafts.ID
          )
      )
  ) AS b ON (b.ID = a.bottle_ID)
  LEFT JOIN BeershopService_Bottles_drafts b_drafts ON (b_drafts.ID = b.ID)
ORDER BY a.ID ASC
LIMIT 1000 OFFSET 0
``` 

Is possible to see that the parser created a weird alias for the entity. And again... I'm not sure if i did something wrong or if it's really a bug. Could you guys take a look?

Tnks.

**Comment by ryegrosT8** [comment]
Hi fellows,

I spent some time trying to figure out what could be the root cause of this issue and I think I found it. 

There are some comments at code that expose the troubles presented by cds cql queries not always providing alias for some entities, that could lead to a runtime error in some cases. Looks like some workarounds are done to prevent those possibilities.

At cds-pg/lib/pg/sql-builder/SelectBuilder.js we have a conditional that provide alias to entities in from clause based on cds original cql. This alias could be the explicit alias for the entity ("element.as") or an alias for a subquery ("as") in a FROM clause.


```javascript
    // an as (alias) should always be passed Postgres need it for its select statements
    if (element.as || as) {
      // identifier
      res.sql += ` ${this._quoteElement(element.as || as)}`
    }
```
The root cause of this issue seems to be the fact that I have a subquery inside of a "CASE" clause in a main “SELECT” clause, so the parser wrongly assign to the table inside the subquery the alias that should be only at the end of the "CASE" clause, once that no explicit alias was assigned to the entity in "FROM" clause ("element.as" === null).

That leads to the wrong query segment below:


```sql
    SELECT ID AS ID,
      name AS name,
      size AS size,
      color AS color,
      $8 AS IsActiveEntity,
      $9 AS HasActiveEntity,
      CASE
        WHEN (
          SELECT 1
          FROM BeershopService_Bottles_drafts HasDraftEntity    -- ####### Wrong alias here (copy of "CASE" alias?) #######
          WHERE (
              BeershopService_Bottles.ID = BeershopService_Bottles_drafts.ID
            )
        ) IS NOT NULL THEN TRUE
        ELSE FALSE
      END AS HasDraftEntity,    -- ########## Alias of "CASE" clause ##################
      (
        SELECT DraftAdministrativeData_DraftUUID AS DraftAdministrativeData_DraftUUID
        FROM BeershopService_Bottles_drafts
        WHERE (
            BeershopService_Bottles.ID = BeershopService_Bottles_drafts.ID
          )
      )
    FROM BeershopService_Bottles
```

I propose a short change in the conditional clause. By debugging the code I was able to see that the variable this._options.objectKey is equal to 'xpr' only in the affected case. Seems that 'xpr' means that we have an expression inside a main "SELECT" clause, in this case, a "CASE" clause with one subquery, I propose to use this variable to help the parser to not assign the wrong alias inside the subquery.

``` javascript
    // an as (alias) should always be passed Postgres need it for its select statements
    if (element.as) {
      // identifier
      res.sql += ` ${this._quoteElement(element.as)}`
    } else {
      // avoid the wrong use of the root alias for entities inside expressions
      if (as && this._options.objectKey !== 'xpr') {
        res.sql += ` ${this._quoteElement(as)}`
      }
    }
``` 

Is this case, the entity inside “FROM” will not receive an alias, but in this specific utilization it doesn’t seems to be a problem to postgres database to not have an alias. It is still unclear to me what cases postgres demands alias, but surely, based on my test coding, this is not one of those cases.

Could you guys point if my analisys is correct before we follow to an "pull request"?

ps: I already commit the changes at my fork (https://github.com/ryegrosT8/cds-pg) , and check that all test cases are running with success.

Thanks in advance.
Rafael Yegros.

**Comment by willemi069808** [comment]
Thank you @ryegrosT8, I had the same issue and your solution worked great!

**Comment by ryegrosT8** [comment]
Fixed
