### ISSUE TITLE
Error: [cds-dbm] - failed to load model undefined (STDERR, APP/TASK/deploy-to-postgresql)#

### ISSUE THREAD

**Issue by bigsmity** [sapmentors/cds-pg#384]
When performing a fresh deployment of our project based on pg-beershop to BTP, we started experiencing this error after 0.1.35 was released.

db-deployer-apt

command in deploy.sh:
npx cds-dbm deploy --load-via delta

Error: [cds-dbm] - failed to load model undefined
at PostgresAdapter.initCds (/home/vcap/deps/1/node_modules/cds-dbm/dist/adapter/BaseAdapter.js:202:19)
at async PostgresAdapter.deploy (/home/vcap/deps/1/node_modules/cds-dbm/dist/adapter/BaseAdapter.js:121:9)
at async exports.handler (/home/vcap/deps/1/node_modules/cds-dbm/dist/cli/deploy.js:38:9)
cds-dbm deploy [services]

We set our dependency directly to 0.1.34 and the error was corrected.

**Comment by gregorwolf** [comment]
Hi @bigsmity,

as you might have noticed the error is coming from cds-dbm. Please check [Cannot read properties of undefined (reading 'build') #294](https://github.com/mikezaschka/cds-dbm/issues/294) I've already filed an incident there. Please help to get it fixed. I can't work on it today.

Best Regards
Gregor

**Comment by gregorwolf** [comment]
Closing as not an issue for cds-pg.
