### ISSUE TITLE
Deep insert not working

### ISSUE THREAD

**Issue by d-sooter** [sapmentors/cds-pg#52]
Deep insert doesnt seem to be working with the postgres database. I tried the same insert with the sqlite db and it works find. 

I was able to take a look at the code and it seems that there is a select that happens before the post and this select is treating the association/composition as a normal field an trying to read it from the database.

https://github.com/sapmentors/cds-pg/blob/3b0de5b3cfa7551216fe459967f62fcf6fb6cb95/lib/pg/execute.js#L51

Because this extra colum is added the and not found the further processing is stopped.

**Comment by d-sooter** [comment]
Issue resolved: fixed managed field issues

**Comment by vobu** [comment]
`test(...)` for deep insert coming by @d-sooter

**Comment by vobu** [comment]
closed via #63
