### ISSUE TITLE
Refactor tests regarding different connection parameters / schema

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/cds-pg#64]
With the latest addition in #63 we now run the complete check 3 times with 3 different database connections. I think we should reduce that and make a test for the different connection posibilities separate from testing then the functionality.

**Comment by vobu** [comment]
definitely. am on it and have already made progress with it. so only a question of when i find the time
-> self-assigning

**Comment by vobu** [comment]
closed via #66
