### ISSUE TITLE
don't trigger release pipeline with specific PRs

### ISSUE THREAD

**Issue by vobu** [sapmentors/cds-pg#65]
the release gh action should not be triggered when 1+ of the below holds true:
- node dependency updates `chore(deps)`
- documentation `docs`

@gregorwolf @d-sooter @mikezaschka any other suggestions?

**Comment by gregorwolf** [comment]
Let's go with this for the moment. Sorry for the spam with the dependabot updates.

**Comment by vobu** [comment]
resolved via https://github.com/sapmentors/cds-pg/commit/e32ce852af2bc682a9d840a3181a19ff680cc84c
